-- Grandfather every account that already exists at the moment login starts
-- enforcing the email_verified gate (see auth.service.ts login()).
--
-- email_verified was added in 20260816000000_add_email_verification_code as
-- a soft, non-gating signal -- every row created before today defaulted to
-- false because the column is brand new, not because those users skipped
-- anything (the verification flow did not exist yet when they signed up).
-- Now that login() checks emailVerified for email/password accounts, a
-- default of false on pre-existing rows would lock out every account created
-- before this migration ran, including already-active production users.
--
-- One-time backfill: mark every currently-existing user as verified. Only
-- rows created AFTER this migration applies can end up with email_verified =
-- false, and those are exactly the accounts the login gate is meant to catch
-- (real new signups that never completed the OTP step).
UPDATE "wawu_users" SET "email_verified" = true WHERE "email_verified" = false;
